### ISSUE TITLE
Test configuration phase

### ISSUE THREAD

**Issue by leodido** [fabbricadigitale/scimd#47]
I have push'd configuration phase for the upcoming server to the **feature/server** branch.

Tests have to be done.

## Phase 1

- [x] call `config()` func and test that it returns a `ServiceProviderConfig` instance
- [x] test a `SchemaRepository` instance containing _x_ `Schema` instances has been created
- [x] test a `ResourceTypeRepository` instance containing _y_ `ResourceType` instances has been created

#### Legend
_x_ := Number of JSON files within default/schemas directory
_y_ := Number of JSON files within default/resources directory

## Phase 2

Note that this step requires some parametrization (path of service provider config JSON) of the `config` function.

- [ ] test panics when wrong path
- [ ] test panics with unmarshalling errors
- [ ] test panics with validation errors
